function LoadPageBooks(searchText, pageNo)
{
    var booksPanel = $("#booksPanel");
    booksPanel.html("<div align=\"center\"><img src=\"/Content/Images/Loading.gif\"/></div>");

    $.ajax({
        url: '/Book/PageBooks/',
        type: "GET",
        data: {
             searchTerm : searchText,
             page: pageNo
        },
        complete: function (jqXHR, status) {
            var htmlContent = jqXHR.responseText;
            var index = htmlContent.indexOf("<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->");
            if (index != -1) {
                htmlContent = htmlContent.substring(0, index);
            }

            booksPanel.html(htmlContent);

            var url =  "/Book/ListBooks?page=" + pageNo;
            if (searchText != null && searchText != '') {
                url = "/Book/ListBooks?searchTerm=" + searchText + "&page=" + pageNo;
            }

            window.history.pushState(null, '', url);
        }
    });
}
