function LoadPageBooks(searchText, pageNo)
{
    var i;
    var pageNumbers = GetSession("BooksPageNumbers");
    for (i = 1; i <= pageNumbers; i++) {
        var pageLink = document.getElementById("pageLink_" + i);
        var hyperLink = document.getElementById("hyperLink_" + i);
        
        if (i == pageNo) {
            pageLink.className = "active";
//            hyperLink.removeAttribute("onclick");
        } else {
            pageLink.removeAttribute("class");
//            if (searchText != null && searchText != '') {
//                hyperLink.onclick = "LoadPageBooks('" + searchText + "', " + pageNo + ")";
//            } else {
//                hyperLink.onclick = "LoadPageBooks('', " + pageNo + ")";
//            }
        }
    }

    var booksPanel = $("#booksPanel");
    booksPanel.html("<div align=\"center\"><img src=\"/Content/Images/Loading.gif\"/ width=\"200px\"></div>");

    $.ajax({
        url: '/Book/PageBooks/',
        type: "GET",
        data: {
             searchTerm : searchText,
             page: pageNo
        },
        complete: function (jqXHR, status) {
            var htmlContent = jqXHR.responseText;
            var index = htmlContent.indexOf("<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->");
            if (index != -1) {
                htmlContent = htmlContent.substring(0, index);
            }

            booksPanel.html(htmlContent);

            var url =  "/Book/ListBooks?page=" + pageNo;
            if (searchText != null && searchText != '') {
                url = "/Book/ListBooks?searchTerm=" + searchText + "&page=" + pageNo;
            }

            window.history.pushState(null, '', url);
        }
    });
}

