function RemoveSomeeServerAds()
{
    var htmlContent = document.documentElement.innerHTML;

    var index = htmlContent.indexOf("<!--SCRIPT GENERATED BY SERVER! PLEASE REMOVE-->");
    if (index != -1) {
        htmlContent = htmlContent.substring(0, index);
    }

    document.documentElement.innerHTML = htmlContent;
}
